version: "3.9"
services:
  api:
    image: dcr-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dcr-network

  db:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=dcr
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 1s
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - dcr-network

networks:
  dcr-network:

volumes:
  mysql-volume:
