// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUserLocation(ctx context.Context, arg CreateUserLocationParams) (sql.Result, error)
	GetUserLocation(ctx context.Context, uid string) (UsersLocation, error)
	GetUserLocationByID(ctx context.Context, id int32) (UsersLocation, error)
	GetUserLocations(ctx context.Context, limit int32) ([]UsersLocation, error)
	GetUserLocationsByCategory(ctx context.Context, arg GetUserLocationsByCategoryParams) ([]UsersLocation, error)
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
